twig:
    default_path: '%kernel.project_dir%/templates'
    form_themes: ['bootstrap_5_layout.html.twig']
    globals:
        menuService: '@App\Service\MenuService'
        chookieService: '@App\Service\ChookieService'

when@test:
    twig:
        strict_variables: true
